// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwawnunqeiyjhbjxlpin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YXdudW5xZWl5amhianhscGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjAyMjEsImV4cCI6MjA2MTkzNjIyMX0.KLV1lsbBGZv__KF1Dx4xN6_tOK5LsHItj31DVYEdYss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);